# site settings
title: Veterinaria
subtitle: FansPet
email: fanspet@gmail.com
description: Veterinaria FansPet comprometidos con la salud de sus mascotas.
baseurl: "/fanspet/" # the subpath of your site, e.g. /blog
url: "http://gusn8.github.io" # the base hostname & protocol for your site
author:
street_address: Ciudad Satélite, Nro 111
city: El Alto
state: BO
zip_code: 591
country: Bolivia
phone: 77798721

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/isabel
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
